export default function handler(req, res) {
  const products = [
    {
      id: 1,
      name: 'Amsterdam Classic 500ml',
      category: 'Classic',
      price: 95000,
      description: 'Tumbler stainless steel premium dengan lapisan vacuum insulation double-wall untuk menjaga minuman tetap segar.',
      longDescription: 'Amsterdam Classic hadir dengan desain minimalis khas Belanda. Teknologi double-wall vacuum insulation menjaga minuman dingin hingga 24 jam dan panas hingga 12 jam. Cocok untuk aktivitas harian dan perjalanan.',
      capacity: '500ml',
      material: 'Stainless Steel 18/8',
      color: 'Navy Blue',
      image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80',
      images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=80'],
      stock: 45,
      rating: 4.8,
      reviewCount: 128,
      badge: 'Best Seller',
      features: ['Double-wall vacuum', 'BPA Free', 'Leak-proof lid', 'Dishwasher safe'],
      sku: 'AMS-CLX-500-NVY',
    },
    {
      id: 2,
      name: 'Amsterdam Premium 750ml',
      category: 'Premium',
      price: 165000,
      description: 'Kapasitas besar dengan teknologi insulasi terbaik untuk menemani petualanganmu seharian penuh.',
      longDescription: 'Amsterdam Premium dirancang untuk mereka yang butuh hidrasi lebih. Kapasitas 750ml cukup untuk satu hari penuh aktivitas. Material stainless 18/8 grade food-safe, bebas BPA.',
      capacity: '750ml',
      material: 'Stainless Steel 18/8',
      color: 'Forest Green',
      image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
      images: ['https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80'],
      stock: 32,
      rating: 4.9,
      reviewCount: 89,
      badge: 'New',
      features: ['Double-wall vacuum', 'BPA Free', 'Wide mouth', 'Carry handle'],
      sku: 'AMS-PRM-750-GRN',
    },
    {
      id: 3,
      name: 'Amsterdam Elite 900ml',
      category: 'Elite',
      price: 175000,
      description: 'Untuk para petualang sejati. Kapasitas 1 liter dengan ketahanan ekstra dan desain ergonomis.',
      longDescription: 'Amsterdam Elite adalah tumbler terbesar dalam koleksi kami. Ideal untuk gym, hiking, dan aktivitas outdoor. Dilengkapi grip ergonomis dan tutup yang aman dari tumpahan.',
      capacity: '900ml',
      material: 'Stainless Steel 18/8',
      color: 'Matte Black',
      image: 'https://images.unsplash.com/photo-1521590832167-7ae0d9f4bb39?auto=format&fit=crop&w=900&q=80',
      images: ['https://images.unsplash.com/photo-1521590832167-7ae0d9f4bb39?auto=format&fit=crop&w=900&q=80'],
      stock: 18,
      rating: 4.7,
      reviewCount: 67,
      features: ['Double-wall vacuum', 'BPA Free', 'Ergonomic grip', 'Straw included'],
      sku: 'AMS-ELT-900-BLK',
    },
  ];

  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Content-Type', 'application/json');
  res.status(200).json({ products });
}
